#!/bin/bash

unset FOAM_INST_DIR;module load PrgEnv-intel-14.0.0.080 impi411;source /home1/share/openfoam/2.3.0/intel/intelmpi/OpenFOAM-2.3.0/etc/bashrc

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=$(getApplication)

NODEFILE=`generate_pbs_nodefile`
cat ${NODEFILE}

(
env
mpirun -np ${SLURM_NTASKS} -machinefile ${NODEFILE} \
 $(getApplication) -parallel
) >& log.${application}.${SLURM_JOB_ID}
