#!/bin/bash

module purge;module load gnu/openmpi165;unset FOAM_INST_DIR;source $HOME/OpenFOAM/OpenFOAM-4.0/etc/bashrc WM_COMPILER=Gcc WM_MPLIB=SYSTEMOPENMPI

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=$(getApplication)

NODEFILE=`generate_pbs_nodefile`
cat ${NODEFILE}

(
env
mpirun -np ${SLURM_NTASKS} -machinefile ${NODEFILE} \
 $(getApplication) -parallel
) >& log.${application}.${SLURM_JOB_ID}
