#!/bin/bash

WM_COMPILER=Gcc48
WM_MPLIB=SYSTEMMVAPICH2MPI2_2_rc1

export MPI_BUFFER_SIZE=20000000
#export MV2_ENABLE_AFFINITY=0

cd $PBS_O_WORKDIR

. /etc/profile.d/modules.sh
module purge
module load mvapich2/2.2rc1/gnu
source ${HOME/\/home/\/lustre}/OpenFOAM/OpenFOAM-2.3.0/etc/bashrc \
    WM_COMPILER=${WM_COMPILER} \
    WM_MPLIB=${WM_MPLIB}

(
    env
    
    mpirun pimpleFoam -parallel
    
) >& log.${PBS_JOBID}

