#!/bin/bash

WM_COMPILER=Icc
WM_MPLIB=SYSTEMOPENMPI

export MPI_BUFFER_SIZE=20000000

cd $PBS_O_WORKDIR

. /etc/profile.d/modules.sh
module purge
module load intel/16.0.3.210
module load openmpi/1.10.2/intel
source ${HOME/\/home/\/lustre}/OpenFOAM/OpenFOAM-2.3.0/etc/bashrc \
    WM_COMPILER=${WM_COMPILER} \
    WM_MPLIB=${WM_MPLIB}

(
    env
    
    mpirun pimpleFoam -parallel
    
) >& log.${PBS_JOBID}

