#!/bin/bash

WM_COMPILER=Gcc48
WM_MPLIB=INTELMPI

export MPI_BUFFER_SIZE=20000000

cd $PBS_O_WORKDIR

. /etc/profile.d/modules.sh
module purge
module load intel-mpi/5.1.3.210
source ${HOME/\/home/\/lustre}/OpenFOAM/OpenFOAM-2.3.0/etc/bashrc \
    WM_COMPILER=${WM_COMPILER} \
    WM_MPLIB=${WM_MPLIB}

(
    env
    
    mpirun pimpleFoam -parallel
    
) >& log.${PBS_JOBID}
