#!/bin/bash

module load gnu/openmpi165
unset FOAM_INST_DIR
source /home1/share/openfoam/2.3.0/gnu/openmpi/OpenFOAM-2.3.0/etc/bashrc

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=$(getApplication)

NODEFILE=`generate_pbs_nodefile`
cat ${NODEFILE}

(
env
mpirun -bind-to-core  -np ${SLURM_NTASKS} -machinefile ${NODEFILE} \
 $(getApplication) -parallel
) >& log.${application}.${SLURM_JOB_ID}
