#!/bin/bash

WM_COMPILER=Gcc48
WM_MPLIB=SGIMPI

export MPI_BUFFER_SIZE=20000000

cd $PBS_O_WORKDIR

. /etc/profile.d/modules.sh
module purge
module load mpt/2.14
source ${HOME/\/home/\/lustre}/OpenFOAM/OpenFOAM-2.3.0/etc/bashrc \
    WM_COMPILER=${WM_COMPILER} \
    WM_MPLIB=${WM_MPLIB}

(
    env
    
    mpiexec_mpt pimpleFoam -parallel
    
) >& log.${PBS_JOBID}

