#!/bin/bash

WM_COMPILER=Icc
WM_MPLIB=SYSTEMHPCXMPI3_3_1

export MPI_BUFFER_SIZE=20000000
export MV2_ENABLE_AFFINITY=0

cd $PBS_O_WORKDIR

. /etc/profile.d/modules.sh
module purge
module load intel/16.0.3.210
module load hpcx/3.3-1.0.0.0/intel
source ${HOME/\/home/\/lustre}/OpenFOAM/OpenFOAM-2.3.0/etc/bashrc \
    WM_COMPILER=${WM_COMPILER} \
    WM_MPLIB=${WM_MPLIB}

(
    env
    
    mpirun pimpleFoam -parallel
    
) >& log.${PBS_JOBID}

