#!/bin/bash

if [ -z "${PBS_JOBID+x}" ] ; then
    PBS_JOBID=$1
else
    cd $PBS_O_WORKDIR
fi

export MPI_BUFFER_SIZE=20000000

. /etc/profile.d/modules.sh
module purge
module load pbsutils
module load openmpi/1.10.2/gnu
. /lustre/app/openfoam/1612/OpenFOAM-v1612+/etc/bashrc

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

log=log.${application}.${PBS_JOBID}
(
    env
    mpirun $application -parallel
    rbstat -s ${PBS_JOBID}    
) >& $log

grep "^End" $log >& /dev/null
[ $? -eq 0 ] && touch $log.done
