#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -rf postProcessing graphs logs vtune
rm -f *.eps *.pdf

# ----------------------------------------------------------------- end-of-file
