#!/bin/bash

if [ -z "${PBS_JOBID+x}" ] ; then
    PBS_JOBID=$1
else
    cd $PBS_O_WORKDIR
fi

export MPI_BUFFER_SIZE=20000000

. /etc/profile.d/modules.sh
module purge
module load pbsutils
module load intel/16.0.3.210
module load mpt/2.14
module load openfoam/3.0.1-mpt

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

log=log.${application}.${PBS_JOBID}
(
    env
    mpiexec_mpt $application -parallel
    rbstat -s ${PBS_JOBID}    
) >& $log

grep "^End" $log >& /dev/null
[ $? -eq 0 ] && touch $log.done
