#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=$(getApplication)

log=log.${application}.$2
(
env
mpirun -np $1 -machinefile hostfile \
$(getApplication) -parallel
) >& $log

grep "^End" $log >& /dev/null
[ $? -eq 0 ] && touch $log.done
